events {}

http {
  #rate limiting, 10m memory size and 10 requests per second, else returns status 429
  limit_req_zone $binary_remote_addr zone=app_limit:10m rate=10r/s;
  limit_req_status 429;

  upstream rails_cluster {
    server rails:3000 max_fails=3 fail_timeout=10s;
  }

  #rails-app
  server {
    listen 80;
    server_name app.localhost localhost rails.localhost;

    limit_req zone=app_limit burst=20 nodelay;

    location / {
      proxy_pass http://rails_cluster;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_http_version 1.1;
      proxy_set_header Connection "";
    }
    
    location /stub_status {
      stub_status;
    }
  }

  #grafana
  server {
    listen 80;
    server_name grafana.localhost;

    auth_basic "Restricted Admin Area";
    auth_basic_user_file /etc/nginx/auth/.htpasswd;

    location / {
      proxy_pass http://grafana:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      #stripping headers so that upstream doesnt try to use it
      proxy_set_header Authorization "";
    }
  }

  #prometheus
  server {
    listen 80;
    server_name prometheus.localhost;

    auth_basic "Restricted Admin Area";
    auth_basic_user_file /etc/nginx/auth/.htpasswd;

    location / {
      proxy_pass http://prometheus:9090;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      #stripping headers so that upstream doesnt try to use it
      proxy_set_header Authorization "";
    }
  }
}